include $(THEOS)/makefiles/common.mk

TWEAK_NAME = OverflowTweak
OverflowTweak_FILES = Tweak.xm
OverflowTweak_LDFLAGS= -undefined dynamic_lookup
OverflowTweak_CFLAGS = -I../../ATV2Includes

include $(THEOS_MAKE_PATH)/tweak.mk
